### ISSUE TITLE
Ingress changes with GA in 1.19

### ISSUE THREAD

**Issue by BretFisher** [BretFisher/kubernetes-mastery#14]
Reported by Daniel:

Ingress resource version has changed from `networking.k8s.io/v1beta1` to `networking.k8s.io/v1`and the YAML spec has changed a bit. Update files and video:

## Slides at https://slides.kubernetesmastery.com/#ingress

- [x] `slides/k8s/ingress.md`
- [ ] `slides/k8smastery/taints.md`
- [x] `slides/k8smastery/ingress.md`

## Manifests:

- [ ] `k8s/canary.yaml`
- [x] `k8s/ingress.yaml`
- [x] `k8s/redirect.yaml`

## Videos:
- [x]  Create Lecture Note with [comment](https://github.com/BretFisher/kubernetes-mastery/issues/14#issuecomment-1007729561)
- [x] Update _k8smastery.com/ic-nginx-lb.yaml_ _k8smastery.com/ic-nginx-hn.yaml_
- [x] 99: [Creating Ingress Resources](https://www.udemy.com/course/kubernetesmastery/learn/lecture/18096459#overview) (we just need a new written lecture to indicate the change, no video re-recording)
- [x] 101: redirect.yaml uses old apiVersion but **file is already updated** @ 5:20 
- [x] 102: `kubectl describe` output shows old apiVersion but this is a **non-issue** @ 2:43
- [x] 106: slides show ingress to be in beta @ 3:00 **Add annotation and update [slides](https://slides.kubernetesmastery.com/#718)**

## Old spec example 

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cheddar
spec:
  rules:
  - host: cheddar.A.B.C.D.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: cheddar
          servicePort: 80
```

## New spec example

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cheddar
spec:
  rules:
  - host: cheddar.A.B.C.D.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cheddar
            port:
              number: 80
```
